controller_manager_ns: /
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - p0_joint
      - p1_joint
      - p2_joint
      - p3_joint
